aws_access_key     = "YOUR_AWS_ACCESS_KEY"
aws_secret_key     = "YOUR_AWS_SECRET_KEY"
aws_session_token  = "YOUR_AWS_SESSION_TOKEN"
cloudflare_email   = "YOUR_CLOUDFLARE_EMAIL"
cloudflare_api_token = "YOUR_CLOUDFLARE_API_TOKEN"
