---
- name: Install Docker and Portainer
  hosts: web_servers
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add Docker APT repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        create: yes

    - name: Update apt package index again after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Show Docker version
      debug:
        var: docker_version.stdout

- name: Install Portainer CE
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: -H unix:///var/run/docker.sock
        
    - name: Open firewall port 9443 for Portainer CE
      ufw:
        rule: allow
        name: '9443'
        port: 9443
        proto: tcp
        state: enabled

    - name: Verify Portainer is running
      uri:
        url: https://localhost:9443
        method: GET
        return_content: yes
        status_code: 200
      register: portainer_check
      failed_when: portainer_check.status != 200
